### ISSUE TITLE
The play sound does not match 3310 accurately

### ISSUE THREAD

**Issue by jpakkane** [zserge/nokia-composer#1]
Great project. It finally got me to fish out some old self-written tunes from my old 3210. I compared the result between the original phone and the web site and there are notable differences.

[Link to original video](https://www.dropbox.com/s/d5uiblryg82fygm/nokia%203210%20music.mp4?dl=0).

[Link to nokia-composer version of Liberty Bell](https://zserge.com/nokia-composer/#eyJicG0iOiIxODAiLCJzb25nIjoiOGMyIDhhMiA4LSA4YTIgOGEyIDgjZzIgOGEyIDhmMyA4LSA4YzIgOGMyIDgtIDhhMiA0I2EyIDgjYTIgNCNhMiA4YzIgMmQzIDhhMiA4ZzIgOC0gOGcyIDhnMiA4I2YyIDhnMiA4ZTMgOC0gOGQzIDgtIDgjYTIgNGEyIDhhMiA0YTIgOCNhMiA0YzNcbiJ9).

There are two notable differences. The original phone plays one or two octaves higher. More importantly, two consecutive notes of the same pitch fuse together in nokia-composer but are clearly distinct on the original phone. Presumably it does some fancy attack thingy at the beginning of every note.

Anyway, this is a really fun thing. Thanks.

**Comment by zserge** [comment]
Thanks for reporting, the octave think can probably be fixed. The base "octave 1" frequency is now C2, but I can make it C3 or C4. It's a matter for 1-2 bytes (those frequencies are higher numbers and have a few more digits).

As for tying the notes - that's because this NokiaComposer plays in "legato" mode where notes last their full duration. I can make it more like "stacatto" mode where note lasts for 3/4 of it's duration. This is also related to #2
